import { createTestCoverageRule } from 'code-review';

// Generated by `review init`. Delete this file to disable the rule, or tune its options —
// see createTestCoverageRule's options for the full list (scope, testLayout, guidelines, ...).
export default createTestCoverageRule({
  goal: 80,
  maxCoverageAttempts: 3,
  maxQualityAttempts: 3,
});
