import { defineSettings } from 'code-review';

// Generated by `review init`. Committed configuration for this workspace — package upgrades
// never rewrite this file. Tune anything here; see the code-review README for every field.
export default defineSettings({
  workspace: { root: '.' },
  providers: {
    claude: { models: { fast: 'haiku', capable: 'sonnet' } },
  },
  permissions: {
    bash: [
      'yarn test *',
      'yarn vitest *',
      'npx vitest *',
      'npm test *',
      'vitest *',
      'git diff *',
      'git status *',
      'git log *',
    ],
  },
  agent: {
    maxBudgetUsdPerAttempt: 1,
    attemptTimeoutMinutes: 10,
    scoreBatchSize: 4,
    concurrency: 1,
  },
});
